version: '3.4'

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - .:/site
      - ./docker-config/site.conf:/etc/nginx/templates/default.conf.template
    depends_on:
      - php
      - mysql
    links:
      - php
      - mysql
  php:
    image: bitnami/php-fpm:8.0
    volumes:
      - .:/site
  mysql:
    image: mysql:latest
    environment:
      MYSQL_USER: "userDBAdmin"
      MYSQL_PASSWORD: "Smuggler-Slimness-Tamper-Operating0-Pliable-Mustiness-Tweed"
      MYSQL_DATABASE: "userDB"
      MYSQL_ROOT_PASSWORD: "Smuggler-Slimness-Tamper-Operating0-Pliable-Mustiness-Tweed"
      MYSQL_ROOT_HOST: "*.*.*.*"
    volumes:
      - ./docker-config/users.sql:/docker-entrypoint-initdb.d/users.sql